import Head from "next/head";
export default function Home(){return <><Head><title>Ania&Władzia | Pracownia Fryzjerska</title><meta name="description" content="Pracownia Fryzjerska Ania&Władzia we Wrocławiu. Kameralny salon przy ul. Marcelego Bacciarellego 17."/><meta name="viewport" content="width=device-width, initial-scale=1"/></Head>
<div class="top">✦ KAMERALNA PRACOWNIA FRYZJERSKA WE WROCŁAWIU ✦</div>
<header><a class="brand" href="#top"><b>A<span>&</span>W</b><strong>Ania&Władzia<small>PRACOWNIA FRYZJERSKA</small></strong></a><nav><a href="#o-nas">O pracowni</a><a href="#oferta">Oferta</a><a href="#opinie">Opinie</a><a href="#kontakt">Kontakt</a></nav><a class="call" href="tel:+48713489455">Zadzwoń</a></header>
<main id="top">
<section class="hero"><div class="copy"><label>WROCŁAW · BISKUPIN</label><h1>Włosy, w których<br><em>czujesz się sobą.</em></h1><p>Kameralna pracownia, w której liczy się dobre cięcie, uważność i atmosfera. Bez pośpiechu. Po prostu dobrze.</p><div class="actions"><a class="btn dark" href="tel:+48713489455">Umów wizytę ↗</a><a href="#kontakt">Jak do nas trafić ↓</a></div><div class="stats"><div><b>4,5/5</b><small>81 opinii w Google</small></div><div><b>45 min</b><small>orientacyjny czas usługi</small></div><div><b>60 zł*</b><small>strzyżenie męskie</small></div></div></div><div class="visual"><div class="portrait"><span>ANW<small>EST. WROCŁAW</small></span></div><div class="note">✂ <b>Mała pracownia.<br>Dużo uwagi.</b></div><div class="stamp">DOBRY<br>KRÓJ<br>LEPSZY<br>NASTRÓJ</div></div></section>
<div class="marquee">STRZYŻENIE <i>✦</i> KOLORYZACJA <i>✦</i> STYLIZACJA <i>✦</i> PIELĘGNACJA <i>✦</i> DOBRY KLIMAT <i>✦</i> STRZYŻENIE <i>✦</i> KOLORYZACJA <i>✦</i></div>
<section id="o-nas" class="section"><label>01 / O PRACOWNI</label><div class="two"><h2>Dwie osoby,<br><em>jedna pracownia.</em></h2><div><p class="lead">Ania&Władzia to miejsce dla tych, którzy lubią, kiedy fryzjer słucha. Tworzymy kameralną przestrzeń, w której można spokojnie porozmawiać o tym, czego naprawdę potrzebują Twoje włosy.</p><p>Salon mieści się przy ul. Marcelego Bacciarellego 17 we Wrocławiu. Dostępne informacje wskazują na ocenę 4,5/5 na podstawie 81 opinii.</p><a class="link" href="#kontakt">Poznaj pracownię ↗</a></div></div></section>
<section id="oferta" class="section services"><div class="heading"><div><label>02 / CO ROBIMY</label><h2>Usługi bez<br><em>kombinowania.</em></h2></div><p>Zakres i cena usługi są ustalane indywidualnie. Zadzwoń, aby potwierdzić aktualną ofertę.</p></div><div class="cards"><article><small>01</small><h3>Strzyżenie</h3><p>Dobre cięcie dopasowane do włosów, kształtu fryzury i Twojego stylu.</p><b>Zapytaj o cenę ↗</b></article><article class="accent"><small>02</small><h3>Koloryzacja</h3><p>Odświeżenie koloru i zmiana, która ma wyglądać dobrze także po wyjściu z salonu.</p><b>Zapytaj o cenę ↗</b></article><article><small>03</small><h3>Stylizacja</h3><p>Fryzura na co dzień, ważne wyjście albo po prostu dzień, w którym chcesz wyglądać świetnie.</p><b>Zapytaj o cenę ↗</b></article></div><p class="fine">* Informacja o cenie około 60 zł pochodzi z opinii klienta z sierpnia 2025. Aktualną cenę najlepiej potwierdzić telefonicznie.</p></section>
<section class="quote"><span>“</span><blockquote>Estetyczny wygląd salonu. Udało się skorzystać ze strzyżenia bez kolejki.</blockquote><small>— opinia klienta w Google</small></section>
<section id="opinie" class="section"><div class="heading"><div><label>03 / GŁOS KLIENTÓW</label><h2>Nie musimy<br><em>mówić za siebie.</em></h2></div><div class="rating"><b>4,5</b><span>★★★★★</span><small>81 opinii</small></div></div><div class="reviews"><article><span>★★★★★</span><p>„Estetyczny wygląd salonu. Udało się skorzystać ze strzyżenia bez kolejki. Cała usługa około 45 minut.”</p><small>Hubert M. · lokalny przewodnik</small></article><article><span>★★★★★</span><p>„Komunikacja z panią fryzjerką bez kłopotu :)”</p><small>fragment opinii Google</small></article><article><span>★★★★★</span><p>„Cena strzyżenia męskiego ... około 60 zł.”</p><small>opinia z sierpnia 2025</small></article></div></section>
<section id="kontakt" class="section contact"><div class="contactbox"><div><label>04 / ZNAJDŹ NAS</label><h2>Wpadnij na<br><em>dobrą fryzurę.</em></h2><p class="address">ul. Marcelego Bacciarellego 17<br>51-649 Wrocław</p><div class="actions"><a class="btn dark" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=Marcelego+Bacciarellego+17%2C+51-649+Wroc%C5%82aw">Wyznacz trasę ↗</a><a class="btn light" href="tel:+48713489455">71 348 94 55</a></div><p class="fine lighttext">Godziny otwarcia warto sprawdzić przed wizytą, ponieważ mogą się zmieniać.</p></div><div class="map"><iframe title="Mapa dojazdu" src="https://www.google.com/maps?q=Marcelego%20Bacciarellego%2017,%2051-649%20Wroc%C5%82aw&output=embed" loading="lazy"></iframe><b>ANIA<br>&<br>WŁADZIA</b></div></div></section>
</main><footer><a class="brand" href="#top"><b>A<span>&</span>W</b><strong>Ania&Władzia<small>PRACOWNIA FRYZJERSKA</small></strong></a><span>Marcelego Bacciarellego 17 · Wrocław</span><a href="tel:+48713489455">71 348 94 55</a><small>© 2026</small></footer></>}